### ISSUE TITLE
Error after running provided script

### ISSUE THREAD

**Issue by redhatlinuxvb** [kenneth-karlsson/Cisecurity#2]
Hi,

Thank you so much for the script. following error occur while running the script. can anyone help here.

root@ubuntu:/opt# chmod +x cis1804.sh
root@ubuntu:/opt# sh cis1804.sh
cis1804.sh: 6: cis1804.sh: [[: not found
cis1804.sh: 61: cis1804.sh: declare: not found
cis1804.sh: 62: cis1804.sh: declare: not found
cis1804.sh: 63: cis1804.sh: declare: not found
cis1804.sh: 79: cis1804.sh: [[: not found
mkdir: cannot create directory ‘./log’: File exists
cis1804.sh: 85: cis1804.sh: 0: not found
cis1804.sh: 89: cis1804.sh: Syntax error: redirection unexpected
root@ubuntu:/opt#

**Comment by kenneth-karlsson** [comment]
This script should be run with bash. Try using ./cis1804.sh instead
I have uploaded new versions for both 1804 and 2004

**Comment by kenneth-karlsson** [comment]
I have added code that checks for bash.
